https:
  port: "8082"

api:
  customer360:
    host: "nto-customer-360-api-v2.us-e2.cloudhub.io"
    port: "443"
    protocol: "HTTPS"
  order:
    host: ""
    port: "443"
    protocol: "HTTPS"
    
app:
  client_id: "c9268556b99848ce935a4b4a0f773dad"
  client_secret: "7E46cb32fc5248F392035702a4CDBA57"
  autodiscovery: "15527008"
  
#Sales Business Group credentials
anypoint:
  platform:
    client_id: "8f8414f80f3b43268a295ff3d2173531"
    client_secret: "36A94A62084d44D9b1d3E7b0D2e56D85"
    visualizer:
      layer: "Experience"
      
      
keystore:
  path: "docker01.domain.local.jks"
  password: "Welcome1"
  
shippingCost: "20"
tax: "0.01"