#%RAML 1.0 Library
uses: 
  common: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/common-library/1.0.11/common-library.raml
  address: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/postal-address-library/1.0.4/postal-address-library.raml
  phone: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/phone-library/1.0.3/phone-library.raml
  email: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/email-library/1.0.2/email-library.raml
  modifiedBy: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/modified-by-library/1.0.4/modified-by-library.raml
  collection: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/collection-library/1.0.27/collection-library.raml
  currency: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/currency-library/1.0.1/currency-library.raml
  links: /exchange_modules/5dfb47dc-12e3-4cac-afc5-a00be32d15d8/hypermedia-library/1.0.4/hypermedia-library.raml

types:
  Account:
    type: object
    properties: 
      sourceSystem?: 
      customerId?: 
        example: "c1"
      accountId?: 
        example: "a1"
      name: 
        example: Mythical
      phone?: 
        type: phone.phone[]
      email?: email.email[]
      postalAddresses?: address.Address[] 
      currency?: currency.Currency
      creditLimitInUSD?:
        type: number
        example: 50000 
      createdDateTime?: 
        type: modifiedBy.modified
      lastModifiedDateTime?: 
        type: modifiedBy.modified
      link?: links.Link
    example: !include examples/member.raml
  
  AccountCollection:
    type:  Account[]
    example: !include examples/collection.raml

  AccountCollectionResponse:
    type: collection.CollectionResponse
    properties:
      accounts: 
        type: Account[]
        required: false
    example: !include examples/collectionResponse.raml