#%RAML 1.0 NamedExample
customerId: c1
accountId: a1
name: Northern Trail Outfitters
phone: 
  - type: Work
    phoneNumber: 415-233-2345
    preferred: true
    doNotCall: false
    doNotText: false
email: 
  - type: Work
    address: brett@ga.com
    preferred: true
    doNotEmail: false
postalAddresses: 
  - addressId: addr1
    type: billing
    addressLines: 
      - 154 Douglas Fir Dr
    city: Waleska
    state: GA
    postalCode: "30183"
    countryName: United States of America
    countryCode: USA
currency:
  code: USD
createdDateTime: 
  onDateTime: 2018-01-01T12:01:01Z
lastModifiedDateTime: 
  onDateTime: 2018-08-01T17:20:30Z
  
